format = """
[](#1E3A8A)\
$os\
$username\
[](bg:#1E40AF fg:#1E3A8A)\
$directory\
[](fg:#1E40AF bg:#2563EB)\
$git_branch\
$git_status\
[](fg:#2563EB bg:#3B82F6)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#3B82F6 bg:#60A5FA)\
$docker_context\
[](fg:#60A5FA bg:#1E3A8A)\
$time\
[ ](fg:#1E3A8A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#1E3A8A"
style_root = "bg:#1E3A8A"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#1E3A8A"
disabled = true # Disabled by default

[directory]
style = "bg:#1E40AF"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#60A5FA"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#2563EB"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#2563EB"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#3B82F6"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1E3A8A"
format = '[ ♥ $time ]($style)'
