format = """
[](#E0F2FE)\
$os\
$username\
[](bg:#7DD3FC fg:#1E293B fg:#1E3A8A)\
$directory\
[](fg:#7DD3FC bg:#0EA5E9 fg:#FFFFFF)\
$git_branch\
$git_status\
[ ](fg:#1E3A8A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#E0F2FE fg:#1E293B"
style_root = "bg:#E0F2FE fg:#1E293B"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#E0F2FE fg:#1E293B"
disabled = true # Disabled by default

[directory]
style = "bg:#7DD3FC fg:#1E293B"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:#0EA5E9 fg:#FFFFFF"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#0EA5E9 fg:#FFFFFF"
format = '[$staged$modified$untracked$ahead_behind ]($style)'
